# Generated by Django 5.0.6 on 2024-05-22 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'Admin Role'), (2, 'Normal User Role')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('profilepic', models.ImageField(blank=True, null=True, upload_to='profilepics/')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('cellnumber', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('deletedAt', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.role')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
