# Generated by Django 5.0.6 on 2024-05-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_role_user_roleid_accesstoken_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roleId',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Normal User')], default=2),
        ),
    ]
